APP_NAME = "VoxGo"
APP_VERSION = "0.2.1"
APP_WEBSITE = "https://voxgo.cn/"
GITHUB_REPOSITORY = "zxbb1190/VoxGo_game_voice_trans"
GITHUB_URL = f"https://github.com/{GITHUB_REPOSITORY}"
SERVICE_NAME = "voxgo"
USER_AGENT = f"{APP_NAME}/{APP_VERSION}"
